#!/usr/bin/env ruby

require 'packageiq/cli'
require 'packageiq/loader'
require 'packageiq/provider/rhel'
require 'packageiq/transport/rabbitmq'
require 'packageiq/version'

# read CLI arguments
options = Packageiq::CLI.read

# load settings from config files
loader = Packageiq::Loader.new(options)
config = loader.load

# setup rabbitmq
rmq = Packageiq::Transport::Rabbitmq.new(config[:rabbitmq])
rmq.start
rmq.create_channel
queue_name  = config[:rabbitmq][:queue]
queue       = rmq.create_queue(queue_name)

# get package inventory
piq       = Packageiq::Provider::RHEL.new
inventory = piq.build_inventory

inventory.each do |package_entry|
  message = Packageiq::Transport::Rabbitmq.serialize(package_entry)
  queue.publish(message,
                routing_key: queue.name,
                type: 'rhel',
                content_type: 'application/json',
                app_id: "piq_rhel #{Packageiq::VERSION}")
end
